from pathlib import Path
import re

p = Path('dev/check/phase7-package/vignettes/simulation-design.Rmd')
s = p.read_text(encoding='utf-8')
a = s.index('# The power runs below')
b = s.index('```', a)
s = s[:a] + s[b:]
s = s.replace('> be smaller than the raw marker count because of dependence. For\n> microsatellites, use the locus count as the primary value and\n> $\\sum_l(K_l-1)$ only as a larger sensitivity value.', '''> be smaller than the raw marker count because of linkage and shared
> population history. No marker-count rule automatically establishes it.
> Distinguish the value that generates variation (`nu`) from the value
> assumed when fitting (`nu_fit`).''')
s = s.replace('ingredients used to build it). This is precisely the object you would otherwise\ncompute from real genotypes with `cov_from_genetic_data()`.', '''ingredients used to build it). It has the same matrix form as a genotype
covariance summary, but its sampling distribution is generated by the model.
Real genotype summaries need not follow that distribution.''')
a = s.index('## The role of effective `nu` in statistical power')
b = s.index('## Comparing sampling strategies and candidate models', a)
s = s[:a] + '''## Separate generating information from assumed information

`nu` controls variation among simulated covariance matrices. `nu_fit` controls
the precision assumed by the fitted likelihood; its default is `nu`. Raising
`nu_fit` while keeping `nu` fixed does not create more informative data. It
can make intervals narrower and increase nominal detections while reducing
coverage. Evaluate that mismatch explicitly:

```{r nu-fit-sensitivity, eval = FALSE}
# These runs use the same seeds and therefore the same simulated responses.
# Increase nsim after checking runtime and convergence on a small pilot.
design <- list(
  theta = theta_true, formula = ~ forestcover + altitude, data = surface,
  sample_sizes = 20, strategies = "spacefill",
  tau = tau_true, sigma = sigma_true, nu = 100,
  nsim = 100, seed = 905,
  control = NewtonRaphsonControl(maxit = 100)
)
matched <- do.call(covariance_response_power, design)
overstated <- do.call(covariance_response_power,
                     c(design, list(nu_fit = 2000)))
rbind(matched = matched$parameter_summary,
      overstated = overstated$parameter_summary)
```

**How to read the output.** Compare fit rate, coverage, and power together.
Similar estimates with narrower intervals under larger `nu_fit` reflect the
assumed precision, not better recovery of the generating process. A high
detection rate accompanied by poor coverage is not a successful design.
Failed and nonconverged fits count as non-detections; inspect their frequency
before interpreting power. Coverage and bias summaries require checking which
replicates supplied valid estimates.

These are runnable study-design recipes rather than stored results. Long
power sweeps are not run during vignette builds, and no hidden precomputed
files are needed to render this guide. Save your configuration, seeds, full
assessment objects, package versions, and convergence diagnostics when running
them. Report Monte Carlo uncertainty: for a proportion `p` estimated from
`B` independent replicates, its approximate Monte Carlo standard error is
`sqrt(p * (1 - p) / B)`.

For covariance simulation, the generating `nu` must be at least the covariance
dimension required by `stats::rWishart()`. That simulation constraint does not
make raw marker counts appropriate fitted effective degrees of freedom.

## Sampling sites and placement

Compare both site count and placement under the same generating scenarios.
More sites can improve recovery, but redundant sites or weak covariate coverage
may add little information. Hold generating and fitting `nu` explicit in each
comparison, include weak-signal scenarios, and assess whether the fitted model
is numerically identifiable. Study-design conclusions remain internal to the
simulated model. Additional validation against misspecified, coalescent, or
individual-based processes is needed before translating them into field targets.

---

''' + s[b:]
# Drop the old precomputed result loaders and plots, which were absent from
# built source archives. Retain clearly labeled runnable summary recipes.
for label in ('power-run-load', 'power-plot'):
    s = re.sub(r'```\{r ' + label + r'[^\n]*\}\n.*?```\n', '', s, flags=re.S)
s = s.replace('eval = have_power', 'eval = FALSE')
s = s.replace('maxit = 10,', 'maxit = 100,')
s = s.replace('  nu         = 100,\n  nsim', '  nu         = 100,\n  nu_fit     = 100,   # change separately to assess overstated precision\n  nsim')
s = s.replace('Because all designs reuse one graph,\nit is fast.', 'The graph is reused across designs, but repeated fitting can still be costly.')
s = s.replace('This vignette uses small `nsim` so it builds relatively quickly.', 'The recipes use small pilot counts; no power sweep is executed at build time.')
s = s.replace('  locus count as the primary microsatellite value and report a sensitivity\n  analysis.', '  a justified range and report sensitivity to both generating `nu` and\n  assumed `nu_fit`.')
s = s.replace('tau = 2, sigma = 1, nu = 100, nsim = 200, seed = 1', 'tau = 2, sigma = 1, nu = 100, nu_fit = 100, nsim = 200, seed = 1')
p.write_text(s, encoding='utf-8')
