.libPaths(c(file.path(getwd(), "dev/check/phase2-library"), .libPaths()))
pkgload::load_all("dev/check/phase3-accepted-package")
scratch <- new.env(parent = asNamespace("terradish"))
sys.source("dev/check/phase3/R/gaussian_scale_profile.R", scratch)
usage <- capture.output(codetools::checkUsage(scratch$gaussian_scale_profile, suppressLocalUnused = TRUE))
print(usage)
stopifnot(length(usage) == 0L)
result <- as.data.frame(testthat::test_file("dev/check/phase3-accepted-package/tests/testthat/test-scale-inference.R", env = scratch, reporter = "summary", stop_on_failure = FALSE))
saveRDS(list(usage = usage, tests = result), "dev/release_0.1.0/phase3_namespace_fix_test.rds")
print(colSums(result[, c("passed", "failed", "error", "warning", "skipped")]))
stopifnot(sum(result$failed) == 0, sum(result$error) == 0)
