// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// amg_reduced_laplacian_create
SEXP amg_reduced_laplacian_create(const arma::vec& conductance, const arma::umat& edge_pairs, const double tol, const int maxit, const int coarse_enough, const int npre, const int npost, const double sa_relax, const double aggr_eps_strong, const bool estimate_spectral_radius, const int power_iters);
RcppExport SEXP _terradish_amg_reduced_laplacian_create(SEXP conductanceSEXP, SEXP edge_pairsSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP coarse_enoughSEXP, SEXP npreSEXP, SEXP npostSEXP, SEXP sa_relaxSEXP, SEXP aggr_eps_strongSEXP, SEXP estimate_spectral_radiusSEXP, SEXP power_itersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type conductance(conductanceSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type edge_pairs(edge_pairsSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const int >::type coarse_enough(coarse_enoughSEXP);
    Rcpp::traits::input_parameter< const int >::type npre(npreSEXP);
    Rcpp::traits::input_parameter< const int >::type npost(npostSEXP);
    Rcpp::traits::input_parameter< const double >::type sa_relax(sa_relaxSEXP);
    Rcpp::traits::input_parameter< const double >::type aggr_eps_strong(aggr_eps_strongSEXP);
    Rcpp::traits::input_parameter< const bool >::type estimate_spectral_radius(estimate_spectral_radiusSEXP);
    Rcpp::traits::input_parameter< const int >::type power_iters(power_itersSEXP);
    rcpp_result_gen = Rcpp::wrap(amg_reduced_laplacian_create(conductance, edge_pairs, tol, maxit, coarse_enough, npre, npost, sa_relax, aggr_eps_strong, estimate_spectral_radius, power_iters));
    return rcpp_result_gen;
END_RCPP
}
// amg_reduced_laplacian_solve
Rcpp::List amg_reduced_laplacian_solve(SEXP solver_ptr, const arma::mat& rhs, Rcpp::Nullable<arma::mat> x0, Rcpp::Nullable<double> tol, Rcpp::Nullable<int> maxit);
RcppExport SEXP _terradish_amg_reduced_laplacian_solve(SEXP solver_ptrSEXP, SEXP rhsSEXP, SEXP x0SEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_ptr(solver_ptrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(amg_reduced_laplacian_solve(solver_ptr, rhs, x0, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// amg_reduced_laplacian_rebuild
Rcpp::List amg_reduced_laplacian_rebuild(SEXP solver_ptr, const arma::vec& conductance, const arma::umat& edge_pairs);
RcppExport SEXP _terradish_amg_reduced_laplacian_rebuild(SEXP solver_ptrSEXP, SEXP conductanceSEXP, SEXP edge_pairsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_ptr(solver_ptrSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type conductance(conductanceSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type edge_pairs(edge_pairsSEXP);
    rcpp_result_gen = Rcpp::wrap(amg_reduced_laplacian_rebuild(solver_ptr, conductance, edge_pairs));
    return rcpp_result_gen;
END_RCPP
}
// cholmod_factor_solve
Rcpp::List cholmod_factor_solve(SEXP factor, const arma::mat& rhs);
RcppExport SEXP _terradish_cholmod_factor_solve(SEXP factorSEXP, SEXP rhsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type factor(factorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type rhs(rhsSEXP);
    rcpp_result_gen = Rcpp::wrap(cholmod_factor_solve(factor, rhs));
    return rcpp_result_gen;
END_RCPP
}
// cholmod_direct_create
SEXP cholmod_direct_create(SEXP matrix, const std::string& factorization, const bool perm);
RcppExport SEXP _terradish_cholmod_direct_create(SEXP matrixSEXP, SEXP factorizationSEXP, SEXP permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type factorization(factorizationSEXP);
    Rcpp::traits::input_parameter< const bool >::type perm(permSEXP);
    rcpp_result_gen = Rcpp::wrap(cholmod_direct_create(matrix, factorization, perm));
    return rcpp_result_gen;
END_RCPP
}
// cholmod_direct_update
Rcpp::List cholmod_direct_update(SEXP solver_ptr, SEXP matrix);
RcppExport SEXP _terradish_cholmod_direct_update(SEXP solver_ptrSEXP, SEXP matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_ptr(solver_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type matrix(matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(cholmod_direct_update(solver_ptr, matrix));
    return rcpp_result_gen;
END_RCPP
}
// cholmod_direct_solve
Rcpp::List cholmod_direct_solve(SEXP solver_ptr, const arma::mat& rhs);
RcppExport SEXP _terradish_cholmod_direct_solve(SEXP solver_ptrSEXP, SEXP rhsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_ptr(solver_ptrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type rhs(rhsSEXP);
    rcpp_result_gen = Rcpp::wrap(cholmod_direct_solve(solver_ptr, rhs));
    return rcpp_result_gen;
END_RCPP
}
// assemble_reduced_laplacian
arma::sp_mat assemble_reduced_laplacian(const arma::vec& conductance, const arma::umat& edge_pairs);
RcppExport SEXP _terradish_assemble_reduced_laplacian(SEXP conductanceSEXP, SEXP edge_pairsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type conductance(conductanceSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type edge_pairs(edge_pairsSEXP);
    rcpp_result_gen = Rcpp::wrap(assemble_reduced_laplacian(conductance, edge_pairs));
    return rcpp_result_gen;
END_RCPP
}
// pcg_reduced_laplacian_ic
Rcpp::List pcg_reduced_laplacian_ic(const arma::mat& rhs, const arma::vec& conductance, const arma::umat& edge_pairs, Rcpp::Nullable<arma::mat> x0, const double tol, const int maxit);
RcppExport SEXP _terradish_pcg_reduced_laplacian_ic(SEXP rhsSEXP, SEXP conductanceSEXP, SEXP edge_pairsSEXP, SEXP x0SEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type conductance(conductanceSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type edge_pairs(edge_pairsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(pcg_reduced_laplacian_ic(rhs, conductance, edge_pairs, x0, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// pcg_reduced_laplacian
Rcpp::List pcg_reduced_laplacian(const arma::mat& rhs, const arma::vec& conductance, const arma::umat& edge_pairs, Rcpp::Nullable<arma::mat> x0, const double tol, const int maxit);
RcppExport SEXP _terradish_pcg_reduced_laplacian(SEXP rhsSEXP, SEXP conductanceSEXP, SEXP edge_pairsSEXP, SEXP x0SEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type conductance(conductanceSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type edge_pairs(edge_pairsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(pcg_reduced_laplacian(rhs, conductance, edge_pairs, x0, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// backpropagate_laplacian_to_conductance
arma::vec backpropagate_laplacian_to_conductance(const arma::mat& tGl, const arma::mat& tGr, const arma::umat& tadj);
RcppExport SEXP _terradish_backpropagate_laplacian_to_conductance(SEXP tGlSEXP, SEXP tGrSEXP, SEXP tadjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type tGl(tGlSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tGr(tGrSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type tadj(tadjSEXP);
    rcpp_result_gen = Rcpp::wrap(backpropagate_laplacian_to_conductance(tGl, tGr, tadj));
    return rcpp_result_gen;
END_RCPP
}
// backpropagate_conductance_to_laplacian
arma::sp_mat backpropagate_conductance_to_laplacian(const arma::vec& dgrad__ddl_dC, const arma::umat& tadj);
RcppExport SEXP _terradish_backpropagate_conductance_to_laplacian(SEXP dgrad__ddl_dCSEXP, SEXP tadjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type dgrad__ddl_dC(dgrad__ddl_dCSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type tadj(tadjSEXP);
    rcpp_result_gen = Rcpp::wrap(backpropagate_conductance_to_laplacian(dgrad__ddl_dC, tadj));
    return rcpp_result_gen;
END_RCPP
}
// laplacian_derivative_matrix_product
arma::mat laplacian_derivative_matrix_product(const arma::vec& dgrad__ddl_dC, const arma::umat& tadj, const arma::mat& G);
RcppExport SEXP _terradish_laplacian_derivative_matrix_product(SEXP dgrad__ddl_dCSEXP, SEXP tadjSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type dgrad__ddl_dC(dgrad__ddl_dCSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type tadj(tadjSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(laplacian_derivative_matrix_product(dgrad__ddl_dC, tadj, G));
    return rcpp_result_gen;
END_RCPP
}
// graph_rhs_matrix_product
arma::mat graph_rhs_matrix_product(const arma::uvec& demes, const int n_vertices, const arma::mat& X);
RcppExport SEXP _terradish_graph_rhs_matrix_product(SEXP demesSEXP, SEXP n_verticesSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type demes(demesSEXP);
    Rcpp::traits::input_parameter< const int >::type n_vertices(n_verticesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_rhs_matrix_product(demes, n_vertices, X));
    return rcpp_result_gen;
END_RCPP
}
// graph_rhs_crossprod
arma::mat graph_rhs_crossprod(const arma::uvec& demes, const int n_vertices, const arma::mat& X);
RcppExport SEXP _terradish_graph_rhs_crossprod(SEXP demesSEXP, SEXP n_verticesSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type demes(demesSEXP);
    Rcpp::traits::input_parameter< const int >::type n_vertices(n_verticesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_rhs_crossprod(demes, n_vertices, X));
    return rcpp_result_gen;
END_RCPP
}
// block_cg_reduced_laplacian
Rcpp::List block_cg_reduced_laplacian(const arma::mat& rhs, const arma::vec& conductance, const arma::umat& edge_pairs, Rcpp::Nullable<arma::mat> x0, const double tol, const int maxit);
RcppExport SEXP _terradish_block_cg_reduced_laplacian(SEXP rhsSEXP, SEXP conductanceSEXP, SEXP edge_pairsSEXP, SEXP x0SEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type conductance(conductanceSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type edge_pairs(edge_pairsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(block_cg_reduced_laplacian(rhs, conductance, edge_pairs, x0, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_terradish_amg_reduced_laplacian_create", (DL_FUNC) &_terradish_amg_reduced_laplacian_create, 11},
    {"_terradish_amg_reduced_laplacian_solve", (DL_FUNC) &_terradish_amg_reduced_laplacian_solve, 5},
    {"_terradish_amg_reduced_laplacian_rebuild", (DL_FUNC) &_terradish_amg_reduced_laplacian_rebuild, 3},
    {"_terradish_cholmod_factor_solve", (DL_FUNC) &_terradish_cholmod_factor_solve, 2},
    {"_terradish_cholmod_direct_create", (DL_FUNC) &_terradish_cholmod_direct_create, 3},
    {"_terradish_cholmod_direct_update", (DL_FUNC) &_terradish_cholmod_direct_update, 2},
    {"_terradish_cholmod_direct_solve", (DL_FUNC) &_terradish_cholmod_direct_solve, 2},
    {"_terradish_assemble_reduced_laplacian", (DL_FUNC) &_terradish_assemble_reduced_laplacian, 2},
    {"_terradish_pcg_reduced_laplacian_ic", (DL_FUNC) &_terradish_pcg_reduced_laplacian_ic, 6},
    {"_terradish_pcg_reduced_laplacian", (DL_FUNC) &_terradish_pcg_reduced_laplacian, 6},
    {"_terradish_backpropagate_laplacian_to_conductance", (DL_FUNC) &_terradish_backpropagate_laplacian_to_conductance, 3},
    {"_terradish_backpropagate_conductance_to_laplacian", (DL_FUNC) &_terradish_backpropagate_conductance_to_laplacian, 2},
    {"_terradish_laplacian_derivative_matrix_product", (DL_FUNC) &_terradish_laplacian_derivative_matrix_product, 3},
    {"_terradish_graph_rhs_matrix_product", (DL_FUNC) &_terradish_graph_rhs_matrix_product, 3},
    {"_terradish_graph_rhs_crossprod", (DL_FUNC) &_terradish_graph_rhs_crossprod, 3},
    {"_terradish_block_cg_reduced_laplacian", (DL_FUNC) &_terradish_block_cg_reduced_laplacian, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_terradish(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
