# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

amg_reduced_laplacian_create <- function(conductance, edge_pairs, tol = 1e-8, maxit = 1000L, coarse_enough = 500L, npre = 1L, npost = 1L, sa_relax = 1.0, aggr_eps_strong = 0.08, estimate_spectral_radius = TRUE, power_iters = 4L) {
    .Call(`_terradish_amg_reduced_laplacian_create`, conductance, edge_pairs, tol, maxit, coarse_enough, npre, npost, sa_relax, aggr_eps_strong, estimate_spectral_radius, power_iters)
}

amg_reduced_laplacian_solve <- function(solver_ptr, rhs, x0 = NULL, tol = NULL, maxit = NULL) {
    .Call(`_terradish_amg_reduced_laplacian_solve`, solver_ptr, rhs, x0, tol, maxit)
}

amg_reduced_laplacian_rebuild <- function(solver_ptr, conductance, edge_pairs) {
    .Call(`_terradish_amg_reduced_laplacian_rebuild`, solver_ptr, conductance, edge_pairs)
}

cholmod_factor_solve <- function(factor, rhs) {
    .Call(`_terradish_cholmod_factor_solve`, factor, rhs)
}

cholmod_direct_create <- function(matrix, factorization = "simplicial_ldl", perm = TRUE) {
    .Call(`_terradish_cholmod_direct_create`, matrix, factorization, perm)
}

cholmod_direct_update <- function(solver_ptr, matrix) {
    .Call(`_terradish_cholmod_direct_update`, solver_ptr, matrix)
}

cholmod_direct_solve <- function(solver_ptr, rhs) {
    .Call(`_terradish_cholmod_direct_solve`, solver_ptr, rhs)
}

assemble_reduced_laplacian <- function(conductance, edge_pairs) {
    .Call(`_terradish_assemble_reduced_laplacian`, conductance, edge_pairs)
}

pcg_reduced_laplacian_ic <- function(rhs, conductance, edge_pairs, x0 = NULL, tol = 1e-8, maxit = 1000L) {
    .Call(`_terradish_pcg_reduced_laplacian_ic`, rhs, conductance, edge_pairs, x0, tol, maxit)
}

pcg_reduced_laplacian <- function(rhs, conductance, edge_pairs, x0 = NULL, tol = 1e-8, maxit = 1000L) {
    .Call(`_terradish_pcg_reduced_laplacian`, rhs, conductance, edge_pairs, x0, tol, maxit)
}

backpropagate_laplacian_to_conductance <- function(tGl, tGr, tadj) {
    .Call(`_terradish_backpropagate_laplacian_to_conductance`, tGl, tGr, tadj)
}

backpropagate_conductance_to_laplacian <- function(dgrad__ddl_dC, tadj) {
    .Call(`_terradish_backpropagate_conductance_to_laplacian`, dgrad__ddl_dC, tadj)
}

laplacian_derivative_matrix_product <- function(dgrad__ddl_dC, tadj, G) {
    .Call(`_terradish_laplacian_derivative_matrix_product`, dgrad__ddl_dC, tadj, G)
}

graph_rhs_matrix_product <- function(demes, n_vertices, X) {
    .Call(`_terradish_graph_rhs_matrix_product`, demes, n_vertices, X)
}

graph_rhs_crossprod <- function(demes, n_vertices, X) {
    .Call(`_terradish_graph_rhs_crossprod`, demes, n_vertices, X)
}

